language: python

python: "3.5"

dist: trusty
sudo: false

services:
    - mongodb
    - elasticsearch
    - redis-server

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    - google-chrome
    packages:
    - mongodb-org-server
    - google-chrome-stable

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.npm

before_install:
    - nvm install 6.11
    - nvm use 6.11
    - npm install -g npm@latest grunt-cli

install:
    - cd server && pip install -r dev-requirements.txt && cd ..
    - cd client && npm install && cd ..

script:
    - cd server && flake8 && cd ..
    - cd client && grunt build && cd ..
    - cd server && python manage.py users:create -u test -p test -e test@localhost --admin && cd ..
